coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: frontend
      paths:
        - frontend/
      statuses:
        - type: project
          target: 80%
    # - name: backend
    #   paths:
    #     - server/
    #   statuses:
    #     - type: project
    #       target: 80%
github_checks:
  annotations: true
