# linting check of radis-app
name: 🌱 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    name: 🧪 frontend-ci
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile
      - name: Linting check
        run: cd frontend && yarn lint
      - name: Type check
        run: cd frontend && yarn type-check
      - name: Run tests
        run: cd frontend && yarn test && yarn test:coverage
      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
      - name: "Report Coverage"
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: './frontend/vite.config.ts'
  backend-test:
    name: 🧪 backend-ci
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd server
          pytest
