name: 📖 Draft Paper

on:
  push:
    branches:
      - main
    paths:
      - 'paper/**'
  pull_request:
    branches:
      - main
    paths:
      - 'paper/**'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: ./paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: paper
          path: ./paper/paper.pdf
